#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Script tự động export cookies từ trình duyệt
"""

import sys
from pathlib import Path

try:
    import browser_cookie3
except ImportError:
    print("❌ Thiếu thư viện browser_cookie3!")
    print("📦 Cài đặt: pip install browser-cookie3")
    sys.exit(1)

from colorama import init, Fore, Style

# Khởi tạo colorama
init(autoreset=True)


def export_cookies_from_browser(browser_name, output_file='youtube_cookies.txt'):
    """
    Export cookies từ trình duyệt
    
    Args:
        browser_name (str): Tên trình duyệt ('chrome', 'edge', 'firefox')
        output_file (str): Tên file output
    """
    print(f"{Fore.CYAN}🍪 Đang export cookies từ {browser_name.title()}...")
    
    try:
        # Lấy cookies từ trình duyệt
        if browser_name == 'chrome':
            cookies = browser_cookie3.chrome(domain_name='youtube.com')
        elif browser_name == 'edge':
            cookies = browser_cookie3.edge(domain_name='youtube.com')
        elif browser_name == 'firefox':
            cookies = browser_cookie3.firefox(domain_name='youtube.com')
        else:
            print(f"{Fore.RED}❌ Trình duyệt không được hỗ trợ: {browser_name}")
            return False
        
        # Chuyển sang list để đếm
        cookie_list = list(cookies)
        
        if not cookie_list:
            print(f"{Fore.YELLOW}⚠️  Không tìm thấy cookies YouTube trong {browser_name.title()}")
            print(f"{Fore.CYAN}   💡 Đảm bảo bạn đã đăng nhập YouTube trên {browser_name.title()}")
            return False
        
        # Lưu cookies vào file (định dạng Netscape)
        output_path = Path(output_file)
        
        with open(output_path, 'w', encoding='utf-8') as f:
            # Header Netscape
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# This file is generated by export_cookies.py\n")
            f.write("# Do not edit.\n\n")
            
            # Ghi từng cookie
            for cookie in cookie_list:
                # Format: domain flag path secure expiration name value
                domain = cookie.domain
                flag = 'TRUE' if domain.startswith('.') else 'FALSE'
                path = cookie.path
                secure = 'TRUE' if cookie.secure else 'FALSE'
                expiration = str(cookie.expires) if cookie.expires else '0'
                name = cookie.name
                value = cookie.value
                
                line = f"{domain}\t{flag}\t{path}\t{secure}\t{expiration}\t{name}\t{value}\n"
                f.write(line)
        
        print(f"{Fore.GREEN}✅ Thành công!")
        print(f"{Fore.GREEN}   • Export được {Style.BRIGHT}{len(cookie_list)} {Fore.GREEN}cookies")
        print(f"{Fore.GREEN}   • Lưu tại: {Style.BRIGHT}{output_path.absolute()}")
        print(f"{Fore.CYAN}   • Dung lượng: {output_path.stat().st_size} bytes")
        
        return True
        
    except Exception as e:
        print(f"{Fore.RED}❌ Lỗi: {str(e)}")
        
        # Gợi ý giải pháp
        error_msg = str(e).lower()
        if 'permission' in error_msg or 'access' in error_msg:
            print(f"\n{Fore.YELLOW}💡 Giải pháp:")
            print(f"{Fore.CYAN}   1. Đóng {browser_name.title()} hoàn toàn")
            print(f"{Fore.CYAN}   2. Chạy lại script này")
        elif 'decrypt' in error_msg:
            print(f"\n{Fore.YELLOW}💡 Giải pháp:")
            print(f"{Fore.CYAN}   1. Cài: pip install pycryptodomex")
            print(f"{Fore.CYAN}   2. Hoặc thử trình duyệt khác (Firefox)")
        
        return False


def main():
    """Hàm chính"""
    print(f"{Fore.MAGENTA}{Style.BRIGHT}")
    print("=" * 60)
    print("🍪 Export YouTube Cookies từ Trình duyệt")
    print("=" * 60)
    print(f"{Style.RESET_ALL}\n")
    
    # Danh sách trình duyệt
    browsers = [
        ('edge', 'Microsoft Edge'),
        ('chrome', 'Google Chrome'),
        ('firefox', 'Mozilla Firefox'),
    ]
    
    print(f"{Fore.CYAN}📋 Chọn trình duyệt:\n")
    for i, (name, display) in enumerate(browsers, 1):
        print(f"{Fore.WHITE}   {i}. {display}")
    
    print()
    choice = input(f"{Fore.YELLOW}Chọn số (1-3): {Style.BRIGHT}").strip()
    
    try:
        index = int(choice) - 1
        if 0 <= index < len(browsers):
            browser_name, display_name = browsers[index]
        else:
            print(f"{Fore.RED}❌ Lựa chọn không hợp lệ!")
            sys.exit(1)
    except ValueError:
        print(f"{Fore.RED}❌ Vui lòng nhập số!")
        sys.exit(1)
    
    print(f"\n{Fore.CYAN}🔍 Đã chọn: {Style.BRIGHT}{display_name}")
    print()
    
    # Kiểm tra đã đóng trình duyệt chưa
    print(f"{Fore.YELLOW}⚠️  QUAN TRỌNG:")
    print(f"{Fore.CYAN}   Đảm bảo bạn đã:")
    print(f"{Fore.CYAN}   1. Đăng nhập YouTube trên {display_name}")
    print(f"{Fore.CYAN}   2. ĐÓNG {display_name} hoàn toàn")
    print()
    
    confirm = input(f"{Fore.YELLOW}Đã sẵn sàng? (Y/n): {Style.BRIGHT}").strip().lower()
    if confirm not in ['', 'y', 'yes', 'có']:
        print(f"{Fore.RED}❌ Đã hủy!")
        sys.exit(0)
    
    print()
    
    # Export cookies
    success = export_cookies_from_browser(browser_name)
    
    if success:
        print(f"\n{Fore.GREEN}{'='*60}")
        print(f"{Fore.GREEN}✅ HOÀN TẤT!")
        print(f"{Fore.GREEN}{'='*60}")
        print(f"\n{Fore.CYAN}📝 Bước tiếp theo:")
        print(f"{Fore.CYAN}   1. File {Style.BRIGHT}youtube_cookies.txt {Fore.CYAN}đã sẵn sàng")
        print(f"{Fore.CYAN}   2. Chạy: {Style.BRIGHT}python download_youtube_mp3.py")
        print(f"{Fore.CYAN}   3. Tool sẽ tự động dùng cookies từ file!")
        print()
        print(f"{Fore.GREEN}💡 Cookies có thể dùng trong 30-90 ngày")
        print(f"{Fore.GREEN}   Khi hết hạn, chỉ cần chạy lại script này!")
    else:
        print(f"\n{Fore.RED}{'='*60}")
        print(f"{Fore.RED}❌ THẤT BẠI!")
        print(f"{Fore.RED}{'='*60}")
        print(f"\n{Fore.CYAN}📖 Xem hướng dẫn chi tiết:")
        print(f"{Fore.CYAN}   File: {Style.BRIGHT}EXPORT_COOKIES.md")
        print()
        print(f"{Fore.YELLOW}💡 Giải pháp thay thế:")
        print(f"{Fore.CYAN}   Dùng Extension 'Get cookies.txt LOCALLY' (dễ hơn)")
        print(f"{Fore.CYAN}   Xem hướng dẫn trong EXPORT_COOKIES.md")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print(f"\n{Fore.YELLOW}Đã hủy!")
        sys.exit(0)
    except EOFError:
        print(f"\n{Fore.RED}Đã hủy!")
        sys.exit(0)



